<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Antevenio '. $this->translate('Expenses Management'))->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/jquery.toastr.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/commons.js')
            ->prependFile($this->basePath() . '/js/router.js')
            ->prependFile($this->basePath() . '/js/views/gastos.js')
            ->prependFile($this->basePath() . '/js/models/gastos.js')
            ->prependFile($this->basePath() . '/js/libs/jquery.toastr.min.js')
            ->prependFile($this->basePath() . '/js/libs/backbone.min.js')
            ->prependFile($this->basePath() . '/js/libs/underscore.min.js')
            ->prependFile($this->basePath() . '/js/libs/jquery.min.js')
            ->prependFile($this->basePath() . '/js/app.js')
        ?>

    </head>
    <body>
    <header id="header">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/logo-antevenio.png') ?>" alt="Antevenio"/>&nbsp;<?php echo $this->translate('Expenses Management') ?></a>
                </div>
            </div>
        </nav>
    </header>

    <main id="main">
        <div class="container">
            <?php //echo $this->content; ?>
            <section id="page"></section>
        </div>
    </main>
    
    <footer id="footer">
        <div class="container">
            <p>&copy; alfonsomartin@gmail.com</p>
        </div>
    </footer>

    <?php echo $this->inlineScript() ?>
    
    </body>
</html>